server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    resolver 169.254.169.253 valid=10s;

    location /api/ {
        set $backend http://learn-ecs-backend.internal:8000;
        proxy_pass $backend;
    }

    location / {
        try_files $uri /index.html;
    }
}
